config/routes.rb
Invoicing::Application.routes.draw do
  

  resources :orders
  resources :articles

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

#DVO
belongs_to :order_line

validates :price, numericality: true
#DVO

end

app/models/order.rb
class Order < ActiveRecord::Base
    #DVO
	has_many :order_lines, inverse_of: :order, dependent: :destroy #to assure that when a Order is destroyed, the order_lines are alos destroyed

	#This creates an order_lines_attributes= method on Order that allows you to create, update and (optionally) destroy order_lines.
	#metoda parametrii symbol, hash
	accepts_nested_attributes_for :order_lines, :allow_destroy => true 
    #DVO
end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
	belongs_to :order , inverse_of: :order_lines #DVO: necessary?? 
	belongs_to :article
	# has_one :article #nu e mai bine sa folosesc has_one? Fiecare OrderLine are un articol

	# default_scope -> { order('created_at DESC') }

	# validates :order_id, presence: true
	validates :quantity, presence: true
	before_save :sync_with_article

	def sync_with_article
		self.article_price=self.article.price
		self.article_title=self.article.title
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  respond_to :html, :xml, :json #DVO

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all #DVO Variables that start with the @ sign, called instance variables, are automatically available in the view
    #DVO
    # respond_to do |format|
    #   format.html
    #   format.json { render :json => @articles }
    #   format.xml { render :xml => @articles}
    # end
    respond_with(@articles) #this is a (nicer) alternative to the code above
    #DVO
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:price, :title, :description)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

# Within Rails' implementation of REST new and create are treated differently.

# An HTTP GET to /resources/new is intended to render a form suitable for creating a new resource, which it does by calling the new action within the controller, which creates a new unsaved record and renders the form.

# An HTTP POST to /resources takes the record created as part of the new action and passes it to the create action within the controller, which then attempts to save it to the database.


  # GET /orders/new
  def new #creaza Order, dar nu salveaza in DB
    @order = Order.new
    3.times { 
      order_line=@order.order_lines.build #DVO pt obiectul order creaza-mi un order_line nou
    }
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create 
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save #salveaza Order-ul in DB ??? atunci salveaza si order_line-urile???
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      # params.require(:order).permit(:client_name, :shipping_address)
      params.require(:order).permit(:client_name, :shipping_address, order_lines_attributes: [:_destroy, :id, :article_id, :order_id, :quantity, :article_price, :article_title])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- DVO -->
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <!-- DVO -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <!-- DVO -->
      <th>Id</th>
      <th>Price</th>
      <th>Title</th>
      <th>Description</th>
      <!-- DVO -->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <!-- DVO -->
        <td><%= article.id %></td>
        <td><%= article.price %>$</td>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <!-- DVO -->
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<!-- DVO -->
<p>
  <strong>Id:</strong>
  <%= @article.id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @article.price %> $
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>
<!-- DVO -->

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Invoicing</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- DVO: se aplica tuturor paginilor aplicatiei -->
<header>
 <ul>
	<li><%=link_to 'Articles', articles_path%></li>
	<li><%=link_to 'Orders', orders_path%></li>
 </ul>	
</header>
<!-- DVO: se aplica tuturor paginilor aplicatiei -->
<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_name %><br>
    <%= f.text_field :client_name %>
  </div>
  <div class="field">
    <%= f.label :shipping_address %><br>
    <%= f.text_area :shipping_address %>
  </div>

  <div class="field">
  <%# =f.label :title %>  
  <%#= collection_select :order_line,:article_id,Article.all,:id,:title,prompt: true %> 
  
  <%# @order.order_lines.each do |order_lines| %>
    <%= f.fields_for :order_lines do |order_line_fields| %>
      <!-- render partial -->
      <%=render 'order_line_partial', :f => order_line_fields %>
    <% end %>
    <br/> 
  <%# end %> 
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_order_line_partial.html.erb

	  <p class="fields">
        <%= f.collection_select :article_id, Article.all, :id, :title %>
        <%= f.text_field :quantity %>
        <%#= f.check_box :_destroy %>
        <%#= f.label :_destroy, "Remove-functional" %>
        <%= f.hidden_field :_destroy %>
        <%= link_to_function "remove-non-functional", "remove_fields(this)" %>
      </p

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Client name</th>
      <th>Shipping address</th>
      <th>Order Lines</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.client_name %></td>
        <td><%= order.shipping_address %></td>
        <td>
            <% order.order_lines.each do |order_line| %>
               <%= order_line.article.title %>
               <%= order_line.article.description %>
               <%= order_line.quantity %>
               <%= order_line.article.price %> <br/>
            <% end %>
        </td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client name:</strong>
  <%= @order.client_name %>
</p>

<p>
  <strong>Shipping address:</strong>
  <%= @order.shipping_address %>
</p>

<p>
   <div class="span8">
    <% if @order.order_lines.any? %>
      <h3>Number of order_lines: <%= @order.order_lines.count %></h3>
      <ol class="order_lines">
      	<% @order.order_lines.each do |order_line| %>
      		<li>
		   		 <%= order_line.article.title %>
		   		 <%= order_line.article.description %>
		   		 <%= order_line.quantity %>
		   		 <%= order_line.article.price %> 
		   	</li>	 
	  	<% end %>
	  </ol>	
    <% end %>
  </div>

</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>